config/routes.rb
Rails.application.routes.draw do
  
  resources :lodgingtypes
  resources :lodgings
  resources :valorar_hs
  resources :reservations
  resources :premiums
  resources :profit
  resources :valorateguests

  get '/premium' => 'premium#index'
  get '/nuevotipo' =>'lodgingtypes#new'
  get '/vertipos'=> 'lodgingtypes#index'
  get '/listahospedajes'=> 'lodgings#index'
  get '/verhospedaje/:id'=> 'lodgings#show'
  get '/lodgingtypes/recuperar/:id' => 'lodgingtypes#recuperar'
  get '/hospedajes/mostrar' => 'lodgings#mostrar'
  get '/hospedajes/valoracionhospedajerecibida' => 'valorar_hs#valoracionhospedajerecibida'

  resources :valorar_hs do
  
    get 'valoracionhospedajerecibida', on: :member

  end

  
  resources :reservations do

    get 'actualizar', on: :member

  end

  resources :lodgingtypes do
 
    get 'recuperar', on: :member 

  end

  resources :lodgings do

    get 'confirmadas', on: :member
    get 'mostrar', on: :member
    get 'reservas', on: :member

  end

  devise_for :users

  root 'welcome#index'

end

app/controllers/lodgingtypes_controller.rb
class LodgingtypesController < ApplicationController
  def index
         @lodgingtype = Lodgingtype.all
  end

  def create
     @lodgingtype = Lodgingtype.new(lodgingtype_params)
           @lodgingtype.enable=true;
          if @lodgingtype.save
             redirect_to lodgingtypes_path
          else
            render :new
          end
  end

  def new
    @lodgingtype = Lodgingtype.new
    @lodgingtype.enable=true;
    @lodgingtype.save
  end

  def edit
   @lodgingtype = Lodgingtype.find(params[:id])
  end

  def show
    @lodgingtype = Lodgingtype.find(params[:id])

  end

  def update
    @lodgingtype = Lodgingtype.find(params[:id])
    if @lodgingtype.update(lodgingtype_params)
      redirect_to lodgingtypes_path
    else
      render :edit
    end
  end


  def destroy
    lodgingtype = Lodgingtype.find(params[:id])

     if  lodgingtype.lodgings.count == 0
        lodgingtype.destroy
        lodgingtype.save
        redirect_to lodgingtypes_path
      else
        lodgingtype.enable=false
        lodgingtype.save
        flash[:danger] = "El tipo de hospedaje borrado contiene hospedajes existentes. Estos apareceran a la hora de buscar por esta categoría"
        redirect_to lodgingtypes_path
      end
  end


  def recuperar
    lodgingtype = Lodgingtype.find(params[:id])
    lodgingtype.enable=true
    lodgingtype.save
    redirect_to lodgingtypes_path
  end


  def lodgingtype_params
      params.require(:lodgingtype).permit(:tipo)
  end

end

app/helpers/lodgingtypes_helper.rb
module LodgingtypesHelper
end

app/views/lodgingtypes/edit.html.erb
<%= form_for @lodgingtype do |f| %>
<%= render 'shared/error_messages', object: f.object %>
<div class="field">
<%= f.label :tipo %>
<%= f.text_field :tipo, placeholder: 'Ingrese el tipo' %>
<%= f.submit 'Guardar' %>
 </div>

<% end %>

<h1> <%= link_to "Atras", root_path, ,class: 'btn btn-primary btn-lg' %> </h1> 

app/views/lodgingtypes/index.html.erb
<table class="table">

	<div>
		<tr>
			<th> </th>
			<th> </th>
			<th> </th>
			<th> </th>
			<th> </th>
			<th> Tipo </th>
			<th> Acciones </th>
		</tr>
		 
			<% @lodgingtype.each do |lodgingtype| %>
				<tr>
					<td> </td>
					<td> </td>
					<td> </td>
					<td> </td>
					<td> </td>
					
				<%if lodgingtype.enable==false %>

					 <td style="color: red"> <%= lodgingtype.tipo %> </td>

					<td> 
					<%= link_to "Recuperar", recuperar_lodgingtype_path(lodgingtype),  class: 'btn btn-danger btn-sm' %>
					
					</td>
				<% else %>
					
					<td> <%= lodgingtype.tipo %> </td>

					<td>
					<%= link_to "Eliminar", lodgingtype, method:   :delete, :data => {:confirm => "Seguro?"}   , class: 'btn btn-danger btn-sm' %>
					<%= link_to "Editar", edit_lodgingtype_path(lodgingtype), class: 'btn btn-info btn-sm' %>

					</td>
				<%end%>
				</tr>

		<% end %>
		<% if @lodgingtype.size == 0 %>
			<tr> <td colspan="3"> No hay tipos de hospedajes para mostrar </td> </tr>
		<% end %>
	</div>

</table>

<h2 style="color: blue"><%= link_to 'Atras',new_lodgingtype_path,class: 'btn btn-primary btn-lg'%></h2>

app/views/lodgingtypes/new.html.erb
<div id = new_lod_type>
<% if @lodgingtype.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% @lodgingtype.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<h3> Nuevo Tipo de Hospedaje </h3>
<%= form_for @lodgingtype, url: lodgingtypes_path do |f| %>
<%= f.label :tipo %>
<%= f.text_field :tipo, placeholder: 'Ingrese el tipo'%>
<%= f.submit 'Guardar' %>
<% end %>
</div>

<h1> <%= link_to "Atras", root_path,class: 'btn btn-primary btn-lg' %> </h1> 

app/views/lodgingtypes/show.html.erb
<h3> Tipo creado </h3>

<p>
 <% if @lodgingtype.enable==true %>
  	<%= @lodgingtype.tipo %>
  <% end %>
</p>