config/routes.rb
Rails.application.routes.draw do
  
  resources :lodgingtypes
  resources :lodgings
  resources :valorar_hs
  resources :reservations
  resources :premiums
  resources :profit
  resources :valorateguests

  get '/premium' => 'premium#index'
  get '/nuevotipo' =>'lodgingtypes#new'
  get '/vertipos'=> 'lodgingtypes#index'
  get '/listahospedajes'=> 'lodgings#index'
  get '/verhospedaje/:id'=> 'lodgings#show'
  get '/lodgingtypes/recuperar/:id' => 'lodgingtypes#recuperar'
  get '/hospedajes/mostrar' => 'lodgings#mostrar'
  get '/hospedajes/valoracionhospedajerecibida' => 'valorar_hs#valoracionhospedajerecibida'

  resources :valorar_hs do
  
    get 'valoracionhospedajerecibida', on: :member

  end

  
  resources :reservations do

    get 'actualizar', on: :member

  end

  resources :lodgingtypes do
 
    get 'recuperar', on: :member 

  end

  resources :lodgings do

    get 'confirmadas', on: :member
    get 'mostrar', on: :member
    get 'reservas', on: :member

  end

  devise_for :users

  root 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		
	end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<p><div id=list_hosp_boton><%= link_to "Ver listado de hospedajes", lodgings_path,class: 'btn btn-success btn-lg'%></p></div>
<div id="bienvenida">
<% if user_signed_in? %>
	 Bienvenido <%= current_user.email %>
	 <% if current_user.es_admin==true%> 
	 	<p> <%= link_to "Agregar un tipo de hospedaje", new_lodgingtype_path  %> </p>
	 	<p> <%= link_to "Lista de tipos de hospedaje", lodgingtypes_path  %> </p>
	 	<p> <%= link_to "Ver ganancia entre dos fechas", profit_index_path  %> </p>
	 <% end %>
	 <%if current_user.es_admin !=true%>
	 	<%if current_user.es_premium!=true%>
 			<p><%= link_to "Ser usuario Premium", edit_premium_path(current_user.id)%></p>
 	 	<%end%>
 	<%end%>
 	<p><%= link_to "Ver reservas hechas", reservations_path%>
 	<p><%= link_to "Ver Valoraciones hechas a hospedajes", valorar_hs_path%>
	<p><%= link_to "Ver Valoraciones recibidas a mis hospedajes", hospedajes_valoracionhospedajerecibida_path%>
	<p><%= link_to "Ver calificaciones recibidas", valorateguests_path%>

 	<p> <%= link_to "Mis hospedajes", mostrar_lodging_path(current_user.lodgings) %> </p>
 	<p><%= link_to "Modificar perfil",edit_user_registration_path%>
	<p><%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete %></p>
<% else %>
	<p><%= link_to "Crea una cuenta", new_user_registration_path, class: 'btn btn-success btn-lg' %></p>
	<p><%= link_to "Logueate", new_user_session_path,  class: 'btn btn-success btn-lg' %></p>
<%end%>
</div>