config/routes.rb
Rails.application.routes.draw do
  
  resources :lodgingtypes
  resources :lodgings
  resources :valorar_hs
  resources :reservations
  resources :premiums
  resources :profit
  resources :valorateguests

  get '/premium' => 'premium#index'
  get '/nuevotipo' =>'lodgingtypes#new'
  get '/vertipos'=> 'lodgingtypes#index'
  get '/listahospedajes'=> 'lodgings#index'
  get '/verhospedaje/:id'=> 'lodgings#show'
  get '/lodgingtypes/recuperar/:id' => 'lodgingtypes#recuperar'
  get '/hospedajes/mostrar' => 'lodgings#mostrar'
  get '/hospedajes/valoracionhospedajerecibida' => 'valorar_hs#valoracionhospedajerecibida'

  resources :valorar_hs do
  
    get 'valoracionhospedajerecibida', on: :member

  end

  
  resources :reservations do

    get 'actualizar', on: :member

  end

  resources :lodgingtypes do
 
    get 'recuperar', on: :member 

  end

  resources :lodgings do

    get 'confirmadas', on: :member
    get 'mostrar', on: :member
    get 'reservas', on: :member

  end

  devise_for :users

  root 'welcome#index'

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	belongs_to :lodging
	belongs_to :user
	has_many :valorateguests, dependent: :destroy

	 # Retorna las reservas confirmadas
  	scope :confirmate, -> { where(confirmate: true) }
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
	def index
     @reservas=Reservation.all
	end
	def show
	end

	def create
      @reserva= Reservation.new(reservas_params)
      @reserva.user = current_user
      @reserva.lodging = $hospedaje
      @reserva.confirmate=false
      @mal=@reserva.dateinit >= @reserva.dateexit
      @tampoco=@reserva.dateinit < Date.today
      if (@mal==true)
        flash[:danger]="Error, Usted a ingresado una fecha de entrada superior/igual a la de salida"
        redirect_to lodgings_path
      
       elsif @tampoco==true
        flash[:danger]="Error, usted ingreso una fecha de ingreso inferior a la actual"
        redirect_to lodgings_path
      
        elsif (@reserva.save)
            flash[:success]="Se hizo el pedido de reserva"
            redirect_to lodgings_path
        else
            render 'new'          
      end  
  end

	def new

	end

  def actualizar
    reserva = Reservation.find(params[:id])
    reserva.confirmate=params[:confirmate]
    reserva.rechazado=params[:rechazado]
    if reserva.save
      redirect_to mostrar_lodging_path
    else
      redirect_to reservas_lodging_path
    end
  end

	def update
	end

	def edit
		$hospedaje= Lodging.find(params[:id])
		@reserva= Reservation.new
		render 'new'
	end


	private
	def reservas_params
      params.require(:reservation).permit(:dateinit, :dateexit)
  	end

end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/index.html.erb
  <table class="table">
  
    <div>
    <tr>

      <th></th>
      <th> Hospedaje </th>
      <th> Acciones </th>
    </tr>
     
      <% current_user.reservations.each do |reserva| %>
        <tr>
 
        
        <% if !reserva.lodging.nil? %>
        <% if reserva.rechazado==false %>
         <%if reserva.lodging.user.es_premium==true && user_signed_in? %>
          <td><%=  image_tag reserva.lodging.url, size: "50x50" %></td>
        <%else %>
          <td> <%= image_tag "https://cdn4.iconfinder.com/data/icons/pictype-free-vector-icons/16/home-128.png",  size: "50x50" %> </td>
        <%end%>
          <td> <%= reserva.lodging.titulo %> </td>

          <td> <%= link_to "Ver Hospedaje", reserva.lodging, class: 'btn btn-info btn-sm' %> 

              <% if ValorarH.where(user: current_user, lodging: reserva.lodging).empty? %>
              <%if reserva.dateexit<=Date.today%>
               <% if reserva.confirmate==true  %>
                  <%= link_to "Valorar", edit_valorar_h_path(reserva.lodging), class: 'btn btn-info btn-sm' %>
               <% end %> 
               <% end %>
               <% end %>
          </td>

        <% end %>
        
        </tr>
    <% end %> 
    <% end %>
    <% if current_user.reservations.size == 0 %>
      <tr> <td colspan="3"> No hay reservas para mostrar </td> </tr>
    <% end %>
  </div>

</table>



<h1> <%= link_to "Atras",root_path , class: 'btn btn-info btn-lg'%> <h1>

app/views/reservations/new.html.erb
<h3> Reservar</h3>
<%= form_for @reserva do |f| %>
<%= f.label "Ingreso" %>
<%= f.date_field :dateinit, :required => true%>
<%= f.label "Salida" %>
<%= f.date_field :dateexit, :required => true %>
<%= f.submit 'Enviar' %>
<% end %>
<h1> <%= link_to "Atras", lodgings_path,class: 'btn btn-info btn-lg' %> </h1>