config/routes.rb
Rails.application.routes.draw do
  
  resources :lodgingtypes
  resources :lodgings
  resources :valorar_hs
  resources :reservations
  resources :premiums
  resources :profit
  resources :valorateguests

  get '/premium' => 'premium#index'
  get '/nuevotipo' =>'lodgingtypes#new'
  get '/vertipos'=> 'lodgingtypes#index'
  get '/listahospedajes'=> 'lodgings#index'
  get '/verhospedaje/:id'=> 'lodgings#show'
  get '/lodgingtypes/recuperar/:id' => 'lodgingtypes#recuperar'
  get '/hospedajes/mostrar' => 'lodgings#mostrar'
  get '/hospedajes/valoracionhospedajerecibida' => 'valorar_hs#valoracionhospedajerecibida'

  resources :valorar_hs do
  
    get 'valoracionhospedajerecibida', on: :member

  end

  
  resources :reservations do

    get 'actualizar', on: :member

  end

  resources :lodgingtypes do
 
    get 'recuperar', on: :member 

  end

  resources :lodgings do

    get 'confirmadas', on: :member
    get 'mostrar', on: :member
    get 'reservas', on: :member

  end

  devise_for :users

  root 'welcome#index'

end

app/models/lodging.rb
class Lodging < ActiveRecord::Base
	belongs_to :lodgingtype
	belongs_to :user
	has_many :comments, dependent: :destroy
	has_many :valorarHs, dependent: :destroy
	has_many :reservations, dependent: :destroy

	validates_presence_of :titulo, message: ":Es requerido este campo"
	validates_uniqueness_of :titulo, message: ":Ya existe este titulo"
	validates_format_of :titulo, with: /\A[a-zA-Z ]+\z/, message: ":Sólo se permiten letras"
	validates_presence_of :detalle, message: ":Es requerido este campo"
	validates_length_of :descripcion, minimum: 10, maximum: 50, message: ":No cumple con la cantidad de caracteres minimos o maximo, 10 a 50"
	validates_presence_of :descripcion, message: ":Es requerido este campo"
	validates_length_of :detalle, minimum: 50, maximum: 256, message: ":No cumple con la cantidad mínima o máxima de caracteres,50 a 256"
	validates_presence_of :zona, message: ":Es requerido este campo"
	validates_format_of :zona, with: /\A[a-zA-Z ]+\z/, message: ":Sólo se permiten letras"
	validates_presence_of :lodgingtype_id, message: ":Es requerido este campo"
	validates_presence_of :cantidaddehuespedes, message: ":Es requerido este campo"
	validates :cantidaddehuespedes, :numericality => {:only_integer => true, message: "Solo se permiten numeros"}
	validates_presence_of :url, message: ":Es requerido este campo"
	
	def self.search(search_titulo,search_cant,search_tipo_id,search_zona,start_date,end_date)
		lodgings = Lodging.all

		if search_titulo.present?
      		lodgings = lodgings.where(["titulo LIKE ? ","%#{search_titulo}%"])
      	end

      	if search_cant.present?
      		lodgings = lodgings.where(cantidaddehuespedes: search_cant)
      	end

      	if search_tipo_id.present?
      		lodgings = lodgings.where(lodgingtype_id: search_tipo_id)
      	end

		if search_zona.present?
      		lodgings = lodgings.where(["zona LIKE ? ","%#{search_zona}%"])
      	end

      	result = [] # En result agregaremos los hospedajes libres
    	lodgings.each do |lodging|
      		result << lodging if lodging.is_free?(start_date,end_date) # Agregamos el hospedaje si está libre
    	end

      	return result	

    end

  	# Recibe como parámetros las fechas en las que se busca 
  	# que esté libre el couch
    def is_free?(start_date,end_date)
    	reservas_del_couch = self.reservations # reservas del couch (por el has_many)
    	reservas_confirmadas = reservas_del_couch.confirmate # solo miramos las confirmadas
    	reservas_confirmadas = reservas_confirmadas.where('? < dateexit', start_date) # from se copiaría en el lugar de '?'
    	reservas_confirmadas = reservas_confirmadas.where('? > dateinit', end_date) # to se copiaría en el lugar de '?'
    
    	# Retorno true o false si el resultado de lo anterior 
    	# está vacío o no
    	return reservas_confirmadas.empty?
    end

    # Retorna los couches que están libres entre 2 fechas
  	# Por una cuestión de simplicidad se realiza iterando sobre 
  	# sobre los couches
  	def self.free_couches(from, to)
    	result = [] # En result agregaremos los hospedajes libres
    	Couch.all.each do |couch|
      		result << couch if couch.is_free?(from, to) # Agregamos el hospedaje si está libre
    	end
  	end
end

app/models/lodgingtype.rb
class Lodgingtype < ActiveRecord::Base
	has_many :lodgings, dependent: :destroy
  	validates_uniqueness_of :tipo, message: ":Ya existe"
  	validates_presence_of :tipo, message: ":Es requerido/a"
  	validates_format_of :tipo, with: /\A[a-zA-Z]+\z/,
  	message: ":Sólo letras permitidas"
end

app/controllers/lodgings_controller.rb
class LodgingsController < ApplicationController
   before_filter :authenticate_user!, except: [:show, :index] 

  def create
    @user = current_user
    @lodgings= Lodging.new(allowed_params)
    @lodgings.user=current_user

    if (@lodgings.save)
      flash[:success] = "Se creo el nuevo hospedaje"
      redirect_to mostrar_lodging_path(current_user.lodgings)
    else
      render 'new'
    end
  end

  def new
    @lodgings= Lodging.new
  end 


  def index
    flash.clear
    @lodgings = Lodging.search(params[:search_titulo], params[:search_cant], params[:search_tipo_id],params[:search_zona],params[:start_date],params[:end_date])
    if params[:search_titulo].present? || params[:search_cant].present? || params[:search_tipo_id].present? || params[:search_zona].present? || params[:start_date].present? || params[:end_date].present?
      @ok = 1
        if params[:start_date] >= params[:end_date]
          flash[:success]="La fecha inicial nunca puede ser mayor o igual a la final"
        end
    end
  end

   def edit
   @lodging = Lodging.find(params[:id])
  end

  def update
    @lodging = Lodging.find(params[:id])
    if @lodging.update(allowed_params)
      render :mostrar
    else
      render :edit
    end
  end

  def show
    @lodgings = Lodging.find(params[:id])
  end


def destroy
        @lodgings = Lodging.find(params[:id])
        @rech=@lodgings.reservations.where(:rechazado => false).count
        @conf=@lodgings.reservations.where(:confirmate => true).count
        @confirmadasentransicion=0
        @lodgings.reservations.each do |reserva|
          if reserva.confirmate == true
            if (Date.today<=reserva.dateexit)
              @confirmadasentransicion=1
            end
          end
        end
        @rechh=@rech-@conf
        if (@rech==0 && @conf== 0 && @confirmadasentransicion==0)
            @lodgings.destroy
            flash[:success] = "Se elimino correctamente el hospedaje"
            redirect_to mostrar_lodging_path(current_user.lodgings)
        elsif @confirmadasentransicion==1
            flash[:danger] = "Este hospedaje posee reservas en transicion, no puede ser eliminado"
            redirect_to mostrar_lodging_path(current_user.lodgings)
        elsif (@rechh==0 && @conf!=0)
            @lodgings.destroy
            flash[:success] = "Se elimino correctamente el hospedaje, que posee reservas caducadas"
            redirect_to mostrar_lodging_path(current_user.lodgings)
        else
          flash[:danger] = "Este hospedaje posee reservas pendientes, no puede ser eliminado"
          redirect_to mostrar_lodging_path(current_user.lodgings)
        end
    end

    def mostrar
      
    end

    def reservas
       @lodging = Lodging.find(params[:id])
    end

    def confirmadas
       @lodging = Lodging.find(params[:id])
    end


 private
  def allowed_params
    params.require(:lodging).permit(:titulo, :descripcion, :detalle, :zona, :url, :urldos, :urltres, :urlcuatro, :lodgingtype_id, :cantidaddehuespedes)
  end
end

app/helpers/lodgings_helper.rb
module LodgingsHelper
end

app/views/lodgings/confirmadas.html.erb
<table class="table">

	<div>
		<tr>
			<th> Solicitante </th>
			<th> Fecha de Ingreso </th>
			<th> Fecha de Salida </th>
			<th> </th>
		</tr>

		<% @lodging.reservations.each do |reservation| %>
			<%if reservation.confirmate==true%>
				<tr>	
				<td><%=  reservation.user.name %></td>
				<td> <%= reservation.dateinit %> </td>
				<td> <%= reservation.dateexit %> </td>
				<%if reservation.dateexit<=Date.today%>
					<%if Valorateguest.where(user: reservation.user, reservation: reservation ).empty?%>
					<td> 
						<%= link_to "Valorar Huesped", edit_valorateguest_path(@lodging, us:reservation.user_id, r: reservation), class: 'btn btn-info btn-sm' %> 		
					</td>
					<%else%>
					<td> ya se valoro</td>
					<%end%>
					</tr>
				<%end%>
				
			<%end%>
		<% end %>

		<% if @lodging.reservations.where(:confirmate=>true).size == 0 %>
			<tr> <td colspan="3"> No hay reservas confirmadas para mostrar </td> </tr>
		<% end %>
	</div>

</table>
<h1> <%= link_to "Atras", mostrar_lodging_path ,class: 'btn btn-primary btn-lg'%> </h1>

app/views/lodgings/edit.html.erb
<%= form_for @lodging do |f| %>

<%= render 'shared/error_messages', object: f.object %>
		 
	<%= f.label :titulo,  class: 'control-label' %>
	<%= f.text_field :titulo, placeholder: 'Ingrese el título', class: 'form-control' %>

	<%= f.label :descripcion, class: 'control-label' %>
	<%= f.text_field :descripcion, placeholder: 'ej: característica o atributo', class: 'form-control' %>
	
	<%= f.label :detalle, class: 'control-label' %>
	<%= f.text_field :detalle, placeholder: 'ej: cantidad habitaciones, servicios,etc', class: 'form-control' %>
	
	<%= f.label :zona, class: 'control-label' %>
	<%= f.text_field :zona, placeholder: 'Ingrese la zona', class: 'form-control' %>
	
	<%= f.label :url, class: 'control-label' %>
	<%= f.text_field :url, :pattern => 'http.+', placeholder: 'ej: copie el url de la imagen aquí', class: 'form-control' %>
	
	<%= f.label :urldos, class: 'control-label' %>
	<%= f.text_field :urldos, placeholder: 'ej: copie el url de la imagen aquí',:pattern=>'http.+',  class: 'form-control' %>

	<%= f.label :urltres, class: 'control-label' %>
	<%= f.text_field :urltres, placeholder: 'ej: copie el url de la imagen aquí',:pattern=>'http.+',  class: 'form-control' %>

	<%= f.label :urlcuatro, class: 'control-label' %>
	<%= f.text_field :urlcuatro, placeholder: 'ej: copie el url de la imagen aquí',:pattern=>'http.+',  class: 'form-control' %>

	<div class="row">
		<div class="col-md-4">
				<%= f.label :lodgingtype_id, 'Tipo de Hospedaje' %>
  				<%= collection_select(:lodging, :lodgingtype_id, Lodgingtype.where(:enable=> true), :id, :tipo, {}, { class: 'form-control'}) %>
  		</div>
  	</div>	


	<%= f.submit 'Guardar', class: 'btn btn-primary btn-lg' %>
	
<% end %>

app/views/lodgings/index.html.erb
<p><h1 style="color: green"> Listado de Hospedajes </h1></p>

<div>
		<% ok = 0 %>
		<%= form_tag lodgings_path, :method => 'get' do%>
			
			<p><%= "Título:"%>
			<%= text_field_tag :search_titulo, params[:search_titulo], placeholder: "Búsqueda por título" %></p>
			<p><%= "Cantidad de personas:"%>
			<%= text_field_tag :search_cant, params[:search_cant], placeholder: "Búsqueda por cantidad de personas" %></p>
			<p><%= "Zona:"%>
			<%= text_field_tag :search_zona, params[:search_zona], placeholder: "Búsqueda por zona" %></p>
			<p><%="Fecha Inicial:"%>             	
			<%= text_field_tag :start_date, Date.today, type:'date' %></p>
			<p><%="Fecha Final:"%> 
			<%= text_field_tag :end_date, Date.today, type:'date' %></p>
			<p><%= "Tipo de hospedaje:"%>
			<%= select_tag :search_tipo_id, options_from_collection_for_select(Lodgingtype.all, 'id', 'tipo', params[:search_tipo_id]), include_blank: true %></p>
			<%= submit_tag "Buscar",class: 'btn btn-success btn-lg'%>
		<% end %>
	</div>

<table class="table">
		<tr>
			<th> </th>
			<th> Título </th>
			<th> Descripción </th>
			<th> Acción </th>
		</tr>

		<% @lodgings.each do |lodging| %>
			<tr>	
				<%if lodging.user.es_premium==true && user_signed_in? %>
					<td><%=  image_tag lodging.url, size: "50x50" %></td>
				<%else %>
					<td> <%= image_tag "https://cdn4.iconfinder.com/data/icons/pictype-free-vector-icons/16/home-128.png",  size: "50x50" %> </td>
				<%end%>
				<td> <%= lodging.titulo %> </td>
				<td> <%= lodging.descripcion %> </td>
				<td> <%= link_to "Más", lodging, class: 'btn btn-info btn-sm' %> </td>
			</tr>
		<% end %>

		<% if @lodgings.size == 0 %>
			<tr> <td colspan="3"> No hay hospedajes para mostrar </td> </tr>
		<% end %>
	

	
</table>
 <% if @ok%>
 	<h1> <%= link_to "Hospedajes", lodgings_path,  class: 'btn btn-success btn-lg'%> </h1> 
 <%end%>
 <h1> <%= link_to "Pagina principal", root_path ,class: 'btn btn-primary btn-lg'%> </h1> 

app/views/lodgings/mostrar.html.erb
<table class="table">

	<div>
		<tr>
			<th> </th>
			<th> Título </th>
			<th> Descripción </th>
			<th> Acción </th>
		</tr>

		<% current_user.lodgings.each do |lodging| %>
			<tr>	
				<%if lodging.user.es_premium==true%>
					<td><%=  image_tag lodging.url, size: "50x50" %></td>
				<%else %>
					<td> <%= image_tag "https://cdn4.iconfinder.com/data/icons/pictype-free-vector-icons/16/home-128.png",  size: "50x50" %> </td>
				<%end%>
				<td> <%= lodging.titulo %> </td>
				<td> <%= lodging.descripcion %> </td>
				<td> 
					<%= link_to "Más", lodging, class: 'btn btn-info btn-sm' %> 
					<%= link_to 'Editar', edit_lodging_path(lodging),  class: 'btn btn-warning btn-sm' %>
					<%= link_to 'Eliminar', lodging, method: :delete, data: {confirm: "Esta seguro que quiere eliminar este hospedaje permanentemente ?"},  class: 'btn btn-danger btn-sm' %>
					<%= link_to "Ver Reservas", reservas_lodging_path(lodging),class: 'btn btn-info btn-sm' %> 
					<%= link_to "Ver Reservas Confirmadas", confirmadas_lodging_path(lodging),class: 'btn btn-info btn-sm' %>

				
				</td>
			</tr>
		<% end %>

		<% if current_user.lodgings.size == 0 %>
			<tr> <td colspan="3"> No hay hospedajes para mostrar </td> </tr>
		<% end %>
	</div>

</table>


 <h1> <%= link_to "Atras", root_path , class: 'btn btn-primary btn-lg'%> </h1> 

 <h1> <%= link_to "Crear Hospedaje", new_lodging_path, class: 'btn btn-success btn-lg' %> </h1>

app/views/lodgings/new.html.erb
<%= form_for @lodgings do |f| %>
	
	 <%= render 'shared/error_messages', object: f.object %>
	<div class="form-group">	
		<%= f.label :titulo,  class: 'control-label' %>
		<%= f.text_field :titulo, placeholder: 'Ingrese el titulo', class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= f.label :descripcion, class: 'control-label' %>
		<%= f.text_field :descripcion, placeholder: 'ej: caracteristica o atributo', class: 'form-control' %>
		<%= f.label :detalle, class: 'control-label' %>
		<%= f.text_field :detalle, placeholder: 'ej: cantidad habitaciones, servicios,etc', class: 'form-control' %>
		<%= f.label :zona, class: 'control-label' %>
		<%= f.text_field :zona, placeholder: 'Ingrese la zona', class: 'form-control' %>
		<%= f.label :cantidad_de_huespedes, class: 'control-label' %>
		<%= f.text_field :cantidaddehuespedes, placeholder: 'ej: 5', class: 'form-control' %>
		<%= f.label :url, class: 'control-label' %>
		<%= f.text_field :url, :pattern => 'http.+', placeholder: 'ej: copie el url de la imagen aqui',  class: 'form-control' %>


		<div class="row">
			<div class="col-md-4">
				<%= f.label :lodgingtype_id, 'Tipo de Hospedaje' %>
  				<%= collection_select(:lodging, :lodgingtype_id, Lodgingtype.where(:enable=> true), :id, :tipo, {}, { class: 'form-control'}) %>
  			</div>
  		</div>	

	</div>

	<%= f.submit 'Crear', class: 'btn btn-primary btn-lg' %>

<% end %>

app/views/lodgings/reservas.html.erb
<p><h1 style="color: green"> Listado de Pedidos de Reserva </h1></p>

<table class="table">

	<div>
		<tr>
			<th> Solicitante </th>
			<th> Fecha de Ingreso </th>
			<th> Fecha de Salida </th>
			<th> </th>
		</tr>
	
		<% @lodging.reservations.each do |reservation| %>
				<%count=0%>
				<% mostrar=false%>
				<%if reservation.confirmate==false && reservation.rechazado==false  %>
					<% @lodging.reservations.each do |reservada| %>
						<%if (reservada.id!=reservation.id)%>
							<% if ((reservation.dateinit>= reservada.dateexit) || (reservation.dateexit<=reservada.dateinit)) && reservada.confirmate==true %>
								<%mostrar=true%>
							<% else%>
								<%if reservada.confirmate==true %>
									<%count=1%>
								<%end%>
							<%end%>
						<%end%>
					<%end%>
				<%else%>
					<%count=1%>
				<%end%>
				<%if mostrar==true || count==0%>
					<tr>
					<td> <%= reservation.user.name %> </td>
					<td> <%= reservation.dateinit %> </td>
					<td> <%= reservation.dateexit %> </td>
					<td> <%= link_to "Aceptar", actualizar_reservation_path(rechazado: false ,confirmate: true, id: reservation), class: 'btn btn-info btn-sm' %> 
						<%= link_to 'Rechazar', actualizar_reservation_path(rechazado: true,confirmate: false, id: reservation), class: 'btn btn-info btn-sm' %> 
					</td>
					</tr>
				<%else%>
					<%if reservation.rechazado==false && reservation.confirmate==false%>
						<tr>
						<td> <%= reservation.user.name %> </td>
						<td> <%= reservation.dateinit %> </td>
						<td> <%= reservation.dateexit %> </td>
						<td> <%= link_to 'Rechazar', actualizar_reservation_path(rechazado: true,confirmate: false, id: reservation), class: 'btn btn-info btn-sm' %> 
						</td>
						</tr>
					<%end%>
				<% end%>

		<%end%>

		<% if @lodging.reservations.size == 0 %>
			<tr> <td colspan="3"> No hay reservas para Mostrar </td> </tr>
		<%else%>
			<% if @lodging.reservations.where(:rechazado=>false, :confirmate=>false).size == 0 %>
				<tr> <td colspan="3"> No hay reservas para mostrar </td> </tr>
			<%end%>
		<% end %>

	</div>
</table>

 <h1> <%= link_to "Atras", mostrar_lodging_path ,class: 'btn btn-primary btn-lg'%> </h1>

app/views/lodgings/show.html.erb
<% if user_signed_in? %>

  <div class="panel panel-default">
    <div class="panel-heading"><HR> </label> <HEAD><h3> <li>Titulo: <%= @lodgings.titulo %></li> </h3></HEAD> <label> </HR></div>
  <div class="panel-body">
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-generic" data-slide-to="1"></li>
      <li data-target="#carousel-example-generic" data-slide-to="2"></li>
      <li data-target="#carousel-example-generic" data-slide-to="3"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <%=  image_tag @lodgings.url,size: "500x400"  %>
        <div class="carousel-caption">
        </div>
      </div>

      <% if !@lodgings.urldos.blank? %>
        <div class="item">
         <%=  image_tag @lodgings.urldos,size: "500x400"  %>
         <div class="carousel-caption">
          </div>
       </div>
      <% end %>

      <% if !@lodgings.urltres.blank? %>
        <div class="item">
         <%=  image_tag @lodgings.urltres,size: "500x400"  %>
         <div class="carousel-caption">
          </div>
       </div>
      <% end %>
      <% if !@lodgings.urlcuatro.blank? %>
        <div class="item">
         <%=  image_tag @lodgings.urlcuatro,size: "500x400"  %>
         <div class="carousel-caption">
          </div>
       </div>
      <% end %>


      </div>


    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
    </a>

  </div> <!-- Carousel -->

    <ul>
          <HR> <li>Descripcion del hospedaje:<%= @lodgings.descripcion %></li> </HR>

          <HR> <li>Detalle del Hospedaje:<%= @lodgings.detalle  %></li> </HR>

          <HR> <li>Zona:<%= @lodgings.zona%></li> </HR>
          
          <HR> <li>Tipo De Hospedaje:<%= @lodgings.lodgingtype.tipo%></li> </HR>

          <HR> <li>Cantidad de huespedes:<%= @lodgings.cantidaddehuespedes%></li> </HR>
          
          <HR> <li> Puntaje <%= @lodgings.valorarHs.average(:promedio) %>

           <% if current_user != @lodgings.user%>

              <% if (current_user.reservations.where(:lodging_id=>@lodgings).count==0) || (current_user.reservations.where(:lodging_id=>@lodgings).last.rechazado==true) || ((current_user.reservations.where(:lodging_id=>@lodgings).last.dateexit<=Date.today) && (current_user.reservations.where(:lodging_id=>@lodgings).last.confirmate==true)) %>
                  <HR> <li> <%= link_to "Reservar", edit_reservation_path(@lodgings), class: 'btn btn-success btn-sm' %>
              <%end%>
          <%end%>

  <div>
      <th> </th>
       <% if @lodgings.comments.size == 0 %>
          <h3> <p> Comentario </p> </h3>
          <p> <td colspan="3"> No hay comentarios para mostrar </td> </p>
      <%end%>


    <% @lodgings.comments.each do |com| %>
      <ul>
        <h3> <p> Comentario </p> <h3>
        <p> <%= com.comentario %> </p>
        <h3> <p> Respuesta </p> <h3>
        <p> <%= com.respuesta%> </p>
      </ul>
    <% end %>

   
  </div>

</ul>

<%else%>
  <h3 style="color: red"> <%= "Si desea acceder al contenido del hospedaje porfavor vuelva a atras e inicie sesion o registrese" %> </h3>
 <%end%>

  </div >

      <h1> <%= link_to "Atras", class: 'btn btn-info btn-lg',:controller => :lodgings, :action => :index %> <h1>
</div>